### ISSUE TITLE
Add support for JSON-LD documents

### ISSUE THREAD

**Issue by stuchalk** [lauriro/json-lite#31] opened 2018-01-27 10:21 UTC
It would be great if you could add support for the JSON-LD file type (https://en.wikipedia.org/wiki/JSON-LD) by both mime-type (application/ld+json) and extension(.jsonld).  Or alternatively add an option in the preferences where users could indicate additional mime-types/extensions that the plugin could be used for.

Thanks for the great plugin!
Stuart

**Comment by lauriro** [comment] 2018-01-27 10:40
Duplicate of #20

It is actually implemented but there are issues with [requesting permissions in Firefox](https://bugzilla.mozilla.org/show_bug.cgi?id=1382953). I am between waiting a fix and reimplement with a workaround.

Meanwhile it is possible to use a help of other extension that was proposed in #13.

**Closed** 2018-01-30 10:13 UTC

**Comment by lauriro** [comment] 2018-02-04 20:18
Implemented in 18.2.0

**Comment by stuchalk** [comment] 2018-02-04 20:53
Works great! Thanks so much !
